folio-org/applications-poc-tools

folio-security/src/main/java/org/folio/security/integration/keycloak/service/KeycloakModuleDescriptorMapper.java
folio-security/src/test/java/org/folio/security/integration/keycloak/service/KeycloakModuleDescriptorMapperTest.java
folio-security/src/test/resources/json/emptyDescriptor.json

Fix Nullpointer in case of empty provides a section of the MD.
Added check to prevent Nullpointer

Fix Nullpointer in case of empty provides section of the MD

---

folio-backend-common/pom.xml
folio-integration-kafka/pom.xml
folio-secret-store/folio-secret-store-common/pom.xml
folio-security/pom.xml

Fixes issue with version during fresh install
- Upgrade folio-testing version for all sub-modules

Fix versions issue during build

---

pom.xml

Build goes with failure. It should be fixed.
- add distribution management

FIX: add distribution management to the pom file

---

folio-backend-common/pom.xml
folio-backend-testing/pom.xml
folio-integration-kafka/pom.xml
folio-secret-store/folio-secret-store-common/pom.xml
folio-secret-store/folio-secret-store-starter/pom.xml
folio-secret-store/pom.xml
folio-security/pom.xml
pom.xml

* [maven-release-plugin] prepare release applications-poc-tools-1.0.0
* [maven-release-plugin] Prepare for next development iteration

Release 1.0.0

---

folio-backend-common/pom.xml
folio-backend-testing/pom.xml
folio-integration-kafka/pom.xml
folio-integration-kong/pom.xml
folio-secret-store/folio-secret-store-common/pom.xml
folio-secret-store/folio-secret-store-starter/pom.xml
folio-secret-store/pom.xml
folio-security/pom.xml
pom.xml

Releases v1.2.0 for `application-poc-tools`

Release 1.2.0

---

folio-backend-common/pom.xml
folio-backend-testing/pom.xml
folio-integration-kafka/pom.xml
folio-integration-kong/pom.xml
folio-secret-store/folio-secret-store-common/pom.xml
folio-secret-store/folio-secret-store-starter/pom.xml
folio-secret-store/pom.xml
folio-security/pom.xml
pom.xml

Release v1.3.0

---

folio-backend-testing/pom.xml
folio-backend-testing/src/main/java/org/folio/test/extensions/impl/KeycloakContainerExtension.java
folio-secret-store/folio-secret-store-starter/pom.xml
folio-security/pom.xml

Rollback testcontainer version of Keycloak to v23

MODUSERSKC-24 Rollback to Keycloak v23 in testcontainer

---

folio-backend-testing/src/main/java/org/folio/test/base/BaseBackendIntegrationTest.java

Log the name of integration test being executed into the log for better visibility of what log lines belong to which test
* log a test name in `@BeforeEach` method of an integration test

MODLOGINKC-12 Write name of integration test method to log

---

folio-backend-testing/src/main/java/org/folio/test/FakeKafkaConsumer.java
folio-integration-kong/src/main/java/org/folio/tools/kong/service/KongGatewayService.java
folio-integration-kong/src/test/java/org/folio/tools/kong/service/KongGatewayServiceTest.java

Fixes error message in KongGatewayService
- Fix typo in KongGatewayService
- Replace ArrayList for Kafka consumer with concurrent version of list

MGRENTITLE-51 Fix error message in KongGatewayService

---

folio-backend-common/pom.xml
folio-backend-testing/pom.xml
folio-integration-kafka/pom.xml
folio-integration-kong/pom.xml
folio-secret-store/folio-secret-store-common/pom.xml
folio-secret-store/folio-secret-store-starter/pom.xml
folio-secret-store/pom.xml
folio-security/pom.xml
folio-tls-utils/pom.xml
pom.xml

- prepare release v1.5.0
- prepare for next development iteration

Release 1.5.0

---

folio-tls-utils/src/main/java/org/folio/common/utils/tls/FipsChecker.java

FIPS Report Output adjusted

---

folio-backend-common/pom.xml
folio-backend-common/src/main/java/org/folio/common/utils/SemverUtils.java
folio-backend-common/src/test/java/org/folio/common/utils/SemverUtilsTest.java

Optimize code usage in the project. 
https://folio-org.atlassian.net/browse/MODSCHED-8
- add semver utils

MODSCHED-8: add SemverUtils

---

folio-backend-common/src/main/java/org/folio/common/utils/FeignClientTlsUtils.java
folio-backend-common/src/test/java/org/folio/common/utils/FeignClientTlsUtilsTest.java

Add TLS support for java.net.http.HttpClient

Add TLS support for java.net.http.HttpClient

---

folio-tls-utils/pom.xml
folio-tls-utils/src/main/java/org/folio/common/utils/tls/FipsChecker.java

Added Method getApprovedSecureRandomSafe()

Added Method getApprovedSecureRandomSafe()

---

folio-secret-store/folio-secret-store-common/src/main/java/org/folio/tools/store/impl/AwsStore.java
folio-secret-store/folio-secret-store-common/src/test/java/org/folio/tools/store/impl/AwsStoreTest.java

_Describe the purpose of the pull request. Include background information if necessary._
_How does this change fulfill the purpose?_

Fixed truststore reading implementation

---

folio-secret-store/folio-secret-store-common/pom.xml
folio-secret-store/folio-secret-store-common/src/main/java/org/folio/tools/store/impl/AwsStore.java

Removes bouncy-castle library from provided dependencies by library
- Move the bouncy castle library to test dependencies
- Slightly refactor code (replace explicit declarations with vars)

MODSIDECAR-43 Move bc-fips library to test dependencies

---

Jenkinsfile
folio-secret-store/README.md
folio-secret-store/folio-secret-store-common/src/main/java/org/folio/tools/store/properties/AwsConfigProperties.java
folio-secret-store/folio-secret-store-common/src/main/java/org/folio/tools/store/utils/SsmClientProvider.java
folio-secret-store/folio-secret-store-common/src/test/java/org/folio/tools/store/utils/SsmClientProviderTest.java

Determine access and secret keys for AWS SSM
_How does this change fulfill the purpose?_

EUREKA-210: determine access and secret keys for AWS SSM

---

folio-security/src/main/java/org/folio/security/integration/keycloak/service/KeycloakModuleDescriptorMapper.java
folio-security/src/test/java/org/folio/security/integration/keycloak/service/KeycloakModuleDescriptorMapperTest.java
folio-security/src/test/resources/json/mappingDescriptor.json

Exclude timers from system resource creation filtering
- adjust filter
- adjust test

APPPOCTOOL-25: exclude timers from system resource creation filtering

---

folio-permission-utils/pom.xml
folio-permission-utils/src/main/java/org/folio/common/utils/permission/PermissionUtils.java
folio-permission-utils/src/main/java/org/folio/common/utils/permission/model/PermissionAction.java
folio-permission-utils/src/main/java/org/folio/common/utils/permission/model/PermissionData.java
folio-permission-utils/src/main/java/org/folio/common/utils/permission/model/PermissionType.java
folio-permission-utils/src/test/java/org/folio/common/utils/permission/PermissionUtilsTest.java
pom.xml

It was decided to extract permission property calculation to application-poc-tools project.
https://folio-org.atlassian.net/browse/EUREKA-240
- add separated folio-permission-utils

EUREKA-240: add permission utils

---

folio-backend-common/pom.xml
folio-backend-testing/pom.xml
folio-integration-kafka/pom.xml
folio-integration-kong/pom.xml
folio-permission-utils/pom.xml
folio-secret-store/folio-secret-store-common/pom.xml
folio-secret-store/folio-secret-store-starter/pom.xml
folio-secret-store/pom.xml
folio-security/pom.xml
folio-tls-utils/pom.xml
pom.xml

Release 1.5.5

---

folio-auth-openid/pom.xml
folio-backend-common/pom.xml
folio-backend-testing/pom.xml
folio-integration-kafka/pom.xml
folio-integration-kong/pom.xml
folio-permission-utils/pom.xml
folio-secret-store/folio-secret-store-common/pom.xml
folio-secret-store/folio-secret-store-starter/pom.xml
folio-secret-store/pom.xml
folio-security/pom.xml
folio-tls-utils/pom.xml
pom.xml

https://folio-org.atlassian.net/browse/APPPOCTOOL-36

Release 1.5.7

---

folio-backend-testing/src/main/java/org/folio/test/extensions/impl/KeycloakContainerExtension.java

Increases Keycloak container version for integration tests
- Increases Keycloak container version for integration tests
- _keycloak-admin-client version has been increased by dependabot already_

APPPOCTOOL-28 Increase keycloak test container to v25.0.6

---

folio-auth-openid/pom.xml
folio-backend-common/pom.xml
folio-backend-testing/pom.xml
folio-integration-kafka/pom.xml
folio-integration-kong/pom.xml
folio-permission-utils/pom.xml
folio-secret-store/folio-secret-store-common/pom.xml
folio-secret-store/folio-secret-store-starter/pom.xml
folio-secret-store/pom.xml
folio-security/pom.xml
folio-tls-utils/pom.xml
pom.xml

https://folio-org.atlassian.net/browse/APPPOCTOOL-39

Release 2.0.0

---

folio-auth-openid/pom.xml
folio-backend-common/pom.xml
folio-backend-testing/pom.xml
folio-integration-kafka/pom.xml
folio-integration-kong/pom.xml
folio-integration-kong/src/main/java/org/folio/tools/kong/service/KongGatewayService.java
folio-integration-kong/src/test/java/org/folio/tools/kong/service/KongGatewayServiceTest.java
folio-permission-utils/pom.xml
folio-secret-store/folio-secret-store-common/pom.xml
folio-secret-store/folio-secret-store-starter/pom.xml
folio-secret-store/pom.xml
folio-security/pom.xml
folio-tls-utils/pom.xml
pom.xml

https://folio-org.atlassian.net/browse/MGRENTITLE-92
Cleanup deprecated Kong route management logic with tenant-specific routes
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do Rally stories exist to update the impacted modules?
- Are the Rally stories under active development?
- Do PRs exist for these changes?
Ideally, all the PRs involved in breaking changes would be merged on the same day to avoid breaking the folio-testing
environment. Communication is paramount if that is to be achieved, especially as the number of …

MGRENTITLE-92: remove tenant-specific routes logic

---

Jenkinsfile

Use Java 21 for building - but keep class file compatibility with Java 17 for backward compatibility.
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do Rally stories exist to update the impacted modules?
- Are the Rally stories under active development?
- Do PRs exist for these changes?
Ideally, all the PRs involved in breaking changes would be merged on the same day to avoid breaking the folio-testing
environment. Communication is paramount if that is to be achieved, especially as the number of inter-module and
inter-team …

APPPOCTOOL-50: 

---

.github/PULL_REQUEST_TEMPLATE.md
NEWS.md

Explain why these changes are needed and link the related issue (e.g., https://folio-org.atlassian.net/browse/PROJ-123).
Provide a brief technical summary of the changes.
---

update pr template

---

folio-backend-common/src/main/java/org/folio/common/domain/model/Dependency.java

[MGRAPPS-57](https://folio-org.atlassian.net/browse/MGRAPPS-57)
Introduce the notion of optional dependencies at the application level
- Updated Dependency schema with a new field "optional"
- Remove optional dependencies from the validations
- Added tests
---

MGRAPPS-57: Introduce optional application dependencies

---

folio-secret-store/folio-secret-store-common/pom.xml

Add excluded Fssp classes to Sonar analysis
US: [FOLIO-4318](https://folio-org.atlassian.net/browse/FOLIO-4318)
* update sonar excludes
---

FOLIO-4318 Add previously excluded Fssp classes to Sonar analysis

---

folio-backend-common/pom.xml
folio-backend-common/src/main/java/org/folio/common/utils/SemverUtils.java

Validation does not work properly for prerelease versions.
- Update semver4j version to 5.8.0
- Use the prerelease flag in the satisfies method call
---

Update semver4j version to 5.8.0 and adjust satisfies method call

---

folio-backend-testing/pom.xml
folio-backend-testing/src/main/java/org/folio/test/extensions/impl/KeycloakContainerExtension.java
folio-security/pom.xml

Revert kc upgrade

---

checkstyle/checkstyle-checker.properties
checkstyle/checkstyle-suppressions.xml
folio-backend-common/src/main/java/org/folio/common/utils/InterfaceComparisonUtils.java
folio-integration-kong/src/main/java/org/folio/tools/kong/service/KongGatewayService.java
folio-security/src/main/java/org/folio/security/service/RoutingEntryMatcher.java
pom.xml

Add method length checkstyle rule and refactor code for compliance
---

feat(checkstyle): add method length checkstyle rule and refactor code for compliance

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/verify-dependent-modules.yml
NEWS.md
README.md
docs/workflows/verify-dependent-modules.md

We are introducing a workflow that helps verify all dependent modules built with changes made in the library.
- add workflow to check dependent modules after applications-poc-tools is changed
- add docs
---

add verify dependent modules workflow

---

.github/PULL_REQUEST_TEMPLATE.md
NEWS.md
README.md

https://folio-org.atlassian.net/browse/APPPOCTOOL-70
Fix typos.
- fix typos
---
> Actions → Verify Dependent Modules → Run workflow → select branch → Run.

APPPOCTOOL-70: fix typos

---

folio-integration-kong/src/main/java/org/folio/tools/kong/configuration/KongRegistrarAutoConfiguration.java
folio-integration-kong/src/main/java/org/folio/tools/kong/exception/TenantRouteUpdateException.java
folio-integration-kong/src/main/java/org/folio/tools/kong/service/KongGatewayService.java
folio-integration-kong/src/main/java/org/folio/tools/kong/service/KongRouteTenantService.java
folio-integration-kong/src/test/java/org/folio/tools/kong/service/KongGatewayServiceTest.java
folio-integration-kong/src/test/java/org/folio/tools/kong/service/KongRouteTenantServiceTest.java

Implement tenant-aware routing management for Kong Gateway integration to
support multi-tenant module deployments. This feature enables dynamic addition
and removal of tenants to existing module routes without requiring full module
re-registration.
Related issue: [MGRAPPS-70](https://folio-org.atlassian.net/browse/MGRAPPS-70)
1. New Service Component:
* Added KongRouteTenantService - a dedicated service for managing tenant expressions in Kong route definitions
* Implements regex-based parsing and manipulation of route expressions to add/remove tenant headers
* Handles edge cases like placeholder tenants when all tenants are removed
2. Exception Handling:
* Introduced TenantRouteUpdateException for specific error handling during tenant route operations
3. Enhanced KongGatewayService:
* …

MGRAPPS-70: Consume entitlement Kafka events for Kong route mgmt
