- folio-backend-testing/pom.xml
- folio-backend-testing/src/main/java/org/folio/test/extensions/impl/KeycloakContainerExtension.java
- folio-security/pom.xml
Upgrade Keycloak version for testing and for folio-security to the latest: `v23.0.3`
- Upgrade Keycloak test container to `v23.0.3`
- Raise version of libraries: `folio-testing`, `folio-security`
> Upgrade Keycloak version to 23.0.3

- folio-backend-common/pom.xml
- folio-backend-testing/pom.xml
- folio-integration-kafka/pom.xml
- folio-secret-store/folio-secret-store-common/pom.xml
- folio-secret-store/folio-secret-store-starter/pom.xml
- folio-secret-store/pom.xml
- folio-security/pom.xml
- pom.xml
Since spring-boot 3.2.0 version has been released the repo should be updated as well.
- upgrade spring-boot to 3.2.0
- fix issues
> APPPOCTOOL-1: upgrade spring boot version to 3.2.0

- folio-backend-testing/src/main/java/org/folio/test/extensions/impl/PostgresContainerExtension.java
Using "alpine" version of postgres in test containers to minimize image size
> Use "alpine" version of postgres in test containers

- folio-security/src/main/java/org/folio/security/integration/keycloak/service/KeycloakImportService.java
- folio-security/src/main/java/org/folio/security/integration/keycloak/service/KeycloakModuleDescriptorMapper.java
- folio-security/src/test/java/org/folio/security/integration/keycloak/service/KeycloakModuleDescriptorMapperTest.java
- folio-security/src/test/resources/json/mappingDescriptor.json
Keycloak resource creation fails if:
- folio_permissions attribute value is longer than 255 symbols
- an endpoint has additional handler in system interfaces (such as _timer)
JIRA: https://issues.folio.org/browse/MGRENTITLE-26
- Store folio_permissions into multiple values
- Remove folio permissions from **Type** field as it's not used currently and it also has a length limit of 255 symbols
- Add support to exclude system interfaces from mapper processing
> [MGRENTITLE-26] Fix Keycloak resources creation issues

- folio-integration-kong/src/main/java/org/folio/tools/kong/service/KongGatewayService.java
- folio-integration-kong/src/test/java/org/folio/tools/kong/service/KongGatewayServiceTest.java
Implements an ability to remove a Kong service using `KongGatewayService`
US: [MGRAPPS-2](https://folio-org.atlassian.net/browse/MGRAPPS-2)
- Implement a method 'deleteService` in `KongGatewayService`
- Add unit tests to verify call to `KongAdminClient`
> MGRAPPS-2 Implement ability to remove service

- folio-backend-testing/pom.xml
- folio-backend-testing/src/main/java/org/folio/test/extensions/impl/KeycloakContainerExtension.java
- folio-security/pom.xml
Upgrade Keycloak c to v23.0.6
_How does this change fulfill the purpose?_
> KEYCLOAK-6 Raise keycloak version to v23.0.6

- folio-security/src/main/java/org/folio/security/configuration/SecurityConfiguration.java
- folio-security/src/main/java/org/folio/security/integration/authtoken/configuration/OkapiSecurityConfiguration.java
- folio-security/src/main/java/org/folio/security/integration/authtoken/service/OkapiAuthorizationService.java
- folio-security/src/main/java/org/folio/security/integration/keycloak/configuration/KeycloakSecurityConfiguration.java
- folio-security/src/main/java/org/folio/security/integration/keycloak/service/KeycloakAuthorizationService.java
- folio-security/src/main/java/org/folio/security/service/AbstractAuthorizationService.java
- folio-security/src/test/java/org/folio/security/filter/AuthorizationFilterTest.java
- folio-security/src/test/java/org/folio/security/integration/authtoken/service/OkapiAuthorizationServiceTest.java
Fixes an issue with routes with prefixes, introduced in mgr-components and deprecated methods in Security configuration
- Fix an issue for routes with prefix by using commong `application.router.path-prefix` variable
- Refactor [SecurityConfiguration.java](https://github.com/folio-org/applications-poc-tools/compare/feature/MGRAPPS-8?expand=1#diff-ffbce3315501d2aad060128a9593632a7c67c384b9dadb0831b0790aea7d632a) by removing all deprecated methods
> MGRAPPS-8 Adjust authorization for routes with prefixes

- .github/CODEOWNERS
- folio-backend-testing/src/main/java/org/folio/test/extensions/impl/WireMockExtension.java
Externizes docker port and network alias for Wiremock container to be accessible for other containers in network
- Expose docker port and network alias for Wiremock container
> APPPOCTOOL-7 Add network alias for WireMockExtension.java

- folio-integration-kong/src/main/java/org/folio/tools/kong/configuration/KongConfigurationProperties.java
- folio-integration-kong/src/main/java/org/folio/tools/kong/model/Service.java
- folio-integration-kong/src/main/java/org/folio/tools/kong/service/KongModuleRegistrar.java
- folio-integration-kong/src/test/java/org/folio/tools/kong/service/KongModuleRegistrarTest.java
Kong timeout should be extended - can't enable all apps for tenants now that mgr-tenant-entitlements is now accessed via Kong.  We get a 504 gateway timeout when enabling applications.
US: [KONG-6](https://folio-org.atlassian.net/browse/KONG-6)
* add new configuration properties for retries/connectTimeout/writeTimeout/readTimeout to `KongConfigurationProperties`
* use the properties while population Kong service
> KONG-6 Kong timeouts should be extended

- folio-backend-common/src/main/java/org/folio/common/domain/model/InterfaceDescriptor.java
- folio-backend-common/src/test/java/org/folio/common/domain/model/InterfaceDescriptorTest.java
- folio-integration-kong/src/main/java/org/folio/tools/kong/service/KongGatewayService.java
- folio-integration-kong/src/test/java/org/folio/tools/kong/service/KongGatewayServiceTest.java
Populate _timer interface routes in Kong so that they become available for mod-scheduler
US: [EUREKA-66](https://folio-org.atlassian.net/browse/EUREKA-66)
* do not ignore `_timer` interface handlers while preparing Kong routes to be created/updated in `KongGatewayService`
this is a **TEMPORARY solution**, should be replaced with well defined approach later
> EUREKA-66 Populate _timer interface routes in Kong

- folio-backend-testing/src/main/java/org/folio/test/FakeKafkaConsumer.java
Don't remove events after each retrieve operation, cause it leads to inconsistent test runs
- Don't remove events after each retrieve operation
- Replace deprecated methods
> MGRENTITLE-21 Stop clearing events after get operation

- folio-tls-utils/pom.xml
- folio-tls-utils/src/main/java/org/folio/common/utils/tls/FipsChecker.java
- pom.xml
Adding a new utility class named 'FipsChecker', which checks and reports the status of various security configurations. It verifies if the system is in Bouncy Castle's Approved Only Mode and whether the JVM is running in FIPS mode. Furthermore, the commit includes the addition of a new 'folio-tls-utils' module.
> Add FipsChecker and folio-tls-utils module in project

- Jenkinsfile
- folio-security/src/main/java/org/folio/security/integration/keycloak/utils/ClientBuildUtils.java
- folio-security/src/test/java/org/folio/security/integration/keycloak/utils/ClientBuildUtilsTest.java
Fix SSLContext creation for the FIPS mode
Apply `buildSslContext` from `FeignClientTlsUtils` since `SSlContextBuilder` does not propagate the type and set the default one PKCS12 instead
> APPPOCTOOL-20: Fix SSLContext creation for the FIPS mode

- folio-backend-testing/pom.xml
- folio-backend-testing/src/main/java/org/folio/test/extensions/impl/KeycloakContainerExtension.java
- folio-backend-testing/src/main/java/org/folio/test/extensions/impl/KeycloakExecutionListener.java
- folio-security/pom.xml
Upgrades keycloak test container and keycloak-admin-client to v25.0.1
- Upgrade keycloak admin client version to `25.0.1`
- Upgrade keycloak test container to `25.0.1`
> APPPOCTOOL-16 Upgrade keycloak to v25.0.1

- folio-integration-kafka/src/main/java/org/folio/integration/kafka/KafkaTopicConfiguration.java
- folio-integration-kafka/src/test/java/org/folio/integration/kafka/KafkaTopicConfigurationTest.java
https://folio-org.atlassian.net/browse/MODLOGINKC-19
There are modules with no non-tenant topics. It should be optional.
- make non-tenant topics creation optional
> MODLOGINKC-19: make non tenant topics optional

- folio-secret-store/folio-secret-store-common/src/main/java/org/folio/tools/store/SecureStoreFactory.java
- folio-secret-store/folio-secret-store-common/src/main/java/org/folio/tools/store/impl/AwsStore.java
- folio-secret-store/folio-secret-store-common/src/main/java/org/folio/tools/store/utils/SsmClientProvider.java
- folio-secret-store/folio-secret-store-common/src/test/java/org/folio/tools/store/impl/AwsStoreTest.java
- folio-secret-store/folio-secret-store-common/src/test/java/org/folio/tools/store/utils/SsmClientProviderTest.java
Refactor `AwsStore` to not reuse existing ssm client, but use a new one for every call
- Refactor `AwsStore` to not reuse existing ssm client, but use a new one for every call
- Update unit tests
> APPPOCTOOL-22 Create SSM Client on every call to avoid connection pool shutdown

- folio-integration-kong/src/main/java/org/folio/tools/kong/service/KongGatewayService.java
The error while Kong service deletion occurs sometimes. 
- add extra login to catch the root cause of error
> log failed Kong service deletion

- folio-backend-common/src/main/java/org/folio/common/domain/model/AnyDescriptor.java
- folio-backend-common/src/main/java/org/folio/common/domain/model/ModuleDescriptor.java
- folio-security/src/test/resources/json/keycloak/client.json
Adds an extension field to the ModuleDescriptor
- Add `extension` field to the ModuleDescriptor
> MGRAPPS-23 Add extension field to the ModuleDescriptor

- folio-secret-store/folio-secret-store-common/src/main/java/org/folio/tools/store/exception/UncheckedVaultException.java
- folio-secret-store/folio-secret-store-common/src/main/java/org/folio/tools/store/impl/VaultStore.java
- folio-secret-store/folio-secret-store-common/src/test/java/org/folio/tools/store/impl/VaultStoreTest.java
- folio-security/src/main/java/org/folio/security/integration/keycloak/configuration/KeycloakDataImportConfiguration.java
https://folio-org.atlassian.net/browse/APPPOCTOOL-52
Log VaultsException error message and stacktrace.
Wrap checked VaultException into UncheckedVaultException,
no longer wrap it into NotFoundException.
Carefully choose how to wrap a checked exception.
> APPPOCTOOL-52: Log VaultExeption stacktrace, NotFoundException wrap

- folio-integration-kong/src/main/java/org/folio/tools/kong/service/KongGatewayService.java
- folio-integration-kong/src/test/java/org/folio/tools/kong/service/KongGatewayServiceTest.java
Kong is no longer responsible for resolving internal system routes (e.g., timer URLs). The internal routing is now fully managed by the Sidecar. Remove route creation in Kong for timer interfaces
US: [APPPOCTOOL-40](https://folio-org.atlassian.net/browse/APPPOCTOOL-40)
* Remove route creation in Kong for timer interfaces. KongGatewayService::prepareRoutes - remove condition for timers
* Update tests
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do Rally stories exist to update the impacted modules?
- Are the Rally stories …
> APPPOCTOOL-40 Integrate Internal Route Discovery into Sidecar with Dynamic Routing Switch, Replacing Kong

- folio-integration-kong/pom.xml
https://lists.apache.org/thread/6ozr91rr9cj5lm0zyhv30bsp317hk5z1 :
> Uncontrolled Resource Consumption vulnerability in Apache Commons IO.
>
> The org.apache.commons.io.input.XmlStreamReader class may excessively consume CPU resources when processing maliciously crafted input.
>
> This issue affects Apache Commons IO: from 2.0 before 2.14.0.
>
> Users are recommended to upgrade to version 2.14.0 or later, which fixes the issue.
Fix vulnerability in dependency commons-io.
Bump minor version of commons-io.
> APPPOCTOOL-53: Upgrade commons-io from 2.11.0 to 2.18.0, CVE-2024-47554

- NEWS.md
- folio-backend-common/src/main/java/org/folio/common/utils/SemverUtils.java
- folio-backend-common/src/test/java/org/folio/common/utils/SemverUtilsTest.java
When extracting name or version part from artifact id, validate that the given artifact contains correct semantic version and raise an exception if it doesn't
US: [MGRENTITLE-113](https://folio-org.atlassian.net/browse/MGRENTITLE-113)
* validate that semantic version is correct when extracting name or version part from artifact id ( `SemverUtils.getVersion()`, `SemverUtils.getName()` methods )
---
> MGRENTITLE-113 Validate semver when getting name or version from artifact id
